using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DesignPatterns.SourceGenerators.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DesignPatterns.SourceGenerators.Syntax;

internal static class GenerateBuilderSyntaxFactory
{
    private const string NotSet = "global::DesignPatterns.Creational.BuilderStepState.NotSet";
    private const string Set = "global::DesignPatterns.Creational.BuilderStepState.Set";

    public static CompilationUnitSyntax CreateCompilationUnit(GenerateBuilderModel model)
    {
        var source = BuildSource(model);
        var tree = CSharpSyntaxTree.ParseText(source);
        var root = (CompilationUnitSyntax)tree.GetRoot();
        return root.NormalizeWhitespace();
    }

    private static string BuildSource(GenerateBuilderModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by DesignPatterns.SourceGenerators.GenerateBuilderGenerator");
        sb.AppendLine();
        sb.AppendLine($"#pragma warning disable {GeneratedCodeHelper.PragmaWarningDisableCodes}");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        var indent = string.Empty;
        if (!string.IsNullOrEmpty(model.NamespaceName))
        {
            sb.AppendLine($"namespace {model.NamespaceName}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var steps = model.Steps.ToList();
        var required = steps.Where(static s => s.Required).ToList();
        var typeParams = required.Select(static s => s.TypeParameterName).ToList();
        var stateType = model.BuilderName + "State";
        var notSetArgs = string.Join(", ", typeParams.Select(_ => NotSet));
        var setArgs = string.Join(", ", typeParams.Select(_ => Set));
        var initialBuilderType = typeParams.Count == 0
            ? model.BuilderName
            : $"{model.BuilderName}<{notSetArgs}>";
        var completeBuilderType = typeParams.Count == 0
            ? model.BuilderName
            : $"{model.BuilderName}<{setArgs}>";

        if (typeParams.Count == 0)
        {
            AppendNonGenericBuilder(sb, indent, model, stateType, initialBuilderType);
        }
        else
        {
            // Arity-0 static entry coexists with arity-N generic builder type.
            sb.Append(indent).AppendLine("/// <summary>");
            sb.Append(indent).AppendLine($"/// Fluent step builder entry point for {model.HolderName}.");
            sb.Append(indent).AppendLine("/// </summary>");
            sb.Append(indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DesignPatterns.SourceGenerators\", \"1.0\")]");
            sb.Append(indent).AppendLine($"public static class {model.BuilderName}");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine("    /// Creates a new builder with no required steps applied.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).AppendLine($"    public static {initialBuilderType} Create() => new {initialBuilderType}(new {stateType}());");
            sb.Append(indent).AppendLine("}");
            sb.AppendLine();
            AppendGenericBuilder(sb, indent, model, typeParams, stateType);
        }

        AppendStateType(sb, indent, stateType, steps);
        AppendExtensions(sb, indent, model, steps, required, typeParams, stateType, completeBuilderType);

        if (!string.IsNullOrEmpty(model.NamespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void AppendNonGenericBuilder(
        StringBuilder sb,
        string indent,
        GenerateBuilderModel model,
        string stateType,
        string initialBuilderType)
    {
        sb.Append(indent).AppendLine("/// <summary>");
        sb.Append(indent).AppendLine($"/// Typed step builder for {model.HolderName}.");
        sb.Append(indent).AppendLine("/// </summary>");
        sb.Append(indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DesignPatterns.SourceGenerators\", \"1.0\")]");
        sb.Append(indent).AppendLine($"public sealed class {model.BuilderName}");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine($"    private readonly {stateType} _state;");
        sb.AppendLine();
        sb.Append(indent).AppendLine($"    internal {model.BuilderName}({stateType} state) => _state = state;");
        sb.AppendLine();
        sb.Append(indent).AppendLine($"    internal {stateType} State => _state;");
        sb.AppendLine();
        sb.Append(indent).AppendLine("    /// <summary>");
        sb.Append(indent).AppendLine("    /// Creates a new builder with no required steps applied.");
        sb.Append(indent).AppendLine("    /// </summary>");
        sb.Append(indent).AppendLine($"    public static {initialBuilderType} Create() => new {initialBuilderType}(new {stateType}());");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendGenericBuilder(
        StringBuilder sb,
        string indent,
        GenerateBuilderModel model,
        List<string> typeParams,
        string stateType)
    {
        var typeParamList = string.Join(", ", typeParams);
        sb.Append(indent).AppendLine("/// <summary>");
        sb.Append(indent).AppendLine($"/// Typed step builder for {model.HolderName}.");
        sb.Append(indent).AppendLine("/// </summary>");
        sb.Append(indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DesignPatterns.SourceGenerators\", \"1.0\")]");
        sb.Append(indent).AppendLine($"public sealed class {model.BuilderName}<{typeParamList}>");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine($"    private readonly {stateType} _state;");
        sb.AppendLine();
        sb.Append(indent).AppendLine($"    internal {model.BuilderName}({stateType} state) => _state = state;");
        sb.AppendLine();
        sb.Append(indent).AppendLine($"    internal {stateType} State => _state;");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendStateType(
        StringBuilder sb,
        string indent,
        string stateType,
        List<BuilderStepModel> steps)
    {
        sb.Append(indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DesignPatterns.SourceGenerators\", \"1.0\")]");
        sb.Append(indent).AppendLine($"internal sealed class {stateType}");
        sb.Append(indent).AppendLine("{");
        foreach (var step in steps)
        {
            var prop = ToPropertyName(step.BindingName);
            var nullableType = step.ValueTypeDisplay.EndsWith("?", StringComparison.Ordinal)
                ? step.ValueTypeDisplay
                : step.ValueTypeDisplay + "?";
            sb.Append(indent).AppendLine($"    public {nullableType} {prop};");
            sb.Append(indent).AppendLine($"    public bool {prop}Set;");
        }

        sb.Append(indent).AppendLine("    public List<string> AppliedOrder = new List<string>();");
        sb.AppendLine();
        sb.Append(indent).AppendLine($"    public {stateType} Clone()");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine($"        var clone = ({stateType})MemberwiseClone();");
        sb.Append(indent).AppendLine("        clone.AppliedOrder = new List<string>(AppliedOrder);");
        sb.Append(indent).AppendLine("        return clone;");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
        sb.AppendLine();
    }

    private static void AppendExtensions(
        StringBuilder sb,
        string indent,
        GenerateBuilderModel model,
        List<BuilderStepModel> steps,
        List<BuilderStepModel> required,
        List<string> typeParams,
        string stateType,
        string completeBuilderType)
    {
        sb.Append(indent).AppendLine("/// <summary>");
        sb.Append(indent).AppendLine($"/// Step and Build extensions for {model.BuilderName}.");
        sb.Append(indent).AppendLine("/// </summary>");
        sb.Append(indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DesignPatterns.SourceGenerators\", \"1.0\")]");
        sb.Append(indent).AppendLine($"public static class {model.BuilderName}Extensions");
        sb.Append(indent).AppendLine("{");

        foreach (var step in steps)
        {
            AppendStepMethod(sb, indent, model, step, steps, required, typeParams);
        }

        AppendBuildMethod(sb, indent, model, steps, completeBuilderType);

        sb.Append(indent).AppendLine("}");
    }

    private static void AppendStepMethod(
        StringBuilder sb,
        string indent,
        GenerateBuilderModel model,
        BuilderStepModel step,
        List<BuilderStepModel> allSteps,
        List<BuilderStepModel> required,
        List<string> typeParams)
    {
        var prop = ToPropertyName(step.BindingName);
        var paramName = ToParameterName(step.BindingName);

        string thisType;
        string returnType;
        string genericClause;
        string summaryKind;

        if (step.Required)
        {
            var thisTypeArgs = string.Join(
                ", ",
                required.Select(r =>
                    string.Equals(r.MethodName, step.MethodName, StringComparison.Ordinal)
                        ? NotSet
                        : r.TypeParameterName));
            var returnTypeArgs = string.Join(
                ", ",
                required.Select(r =>
                    string.Equals(r.MethodName, step.MethodName, StringComparison.Ordinal)
                        ? Set
                        : r.TypeParameterName));
            var freeParams = required
                .Where(r => !string.Equals(r.MethodName, step.MethodName, StringComparison.Ordinal))
                .Select(r => r.TypeParameterName)
                .ToList();
            genericClause = freeParams.Count == 0 ? string.Empty : "<" + string.Join(", ", freeParams) + ">";
            thisType = $"{model.BuilderName}<{thisTypeArgs}>";
            returnType = $"{model.BuilderName}<{returnTypeArgs}>";
            summaryKind = "required";
        }
        else if (typeParams.Count == 0)
        {
            thisType = model.BuilderName;
            returnType = model.BuilderName;
            genericClause = string.Empty;
            summaryKind = "optional";
        }
        else
        {
            var open = string.Join(", ", typeParams);
            thisType = $"{model.BuilderName}<{open}>";
            returnType = thisType;
            genericClause = "<" + open + ">";
            summaryKind = "optional";
        }

        sb.Append(indent).AppendLine("    /// <summary>");
        sb.Append(indent).AppendLine($"    /// Applies the {summaryKind} '{step.MethodName}' step.");
        sb.Append(indent).AppendLine("    /// </summary>");
        sb.Append(indent).AppendLine(
            $"    public static {returnType} {step.MethodName}{genericClause}(this {thisType} builder, {step.ValueTypeDisplay} {paramName})");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var state = builder.State.Clone();");
        if (!step.Required)
        {
            sb.Append(indent).AppendLine($"        if (state.{prop}Set)");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine(
                $"            throw new InvalidOperationException(\"Step '{step.MethodName}' has already been applied.\");");
            sb.Append(indent).AppendLine("        }");
        }

        AppendConstraintGuards(sb, indent, step, allSteps);

        sb.Append(indent).AppendLine($"        state.{prop} = {paramName};");
        sb.Append(indent).AppendLine($"        state.{prop}Set = true;");
        sb.Append(indent).AppendLine($"        state.AppliedOrder.Add(\"{step.MethodName}\");");
        sb.Append(indent).AppendLine($"        return new {returnType}(state);");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();
    }

    private static void AppendConstraintGuards(
        StringBuilder sb,
        string indent,
        BuilderStepModel step,
        List<BuilderStepModel> allSteps)
    {
        if (!string.IsNullOrEmpty(step.After))
        {
            var after = allSteps.FirstOrDefault(s =>
                string.Equals(s.MethodName, step.After, StringComparison.Ordinal)
                || string.Equals(s.BindingName, step.After, StringComparison.OrdinalIgnoreCase));
            if (after.MethodName is not null)
            {
                sb.Append(indent).AppendLine(
                    $"        if (!state.AppliedOrder.Contains(\"{after.MethodName}\"))");
                sb.Append(indent).AppendLine("        {");
                sb.Append(indent).AppendLine(
                    $"            throw new InvalidOperationException(\"Step '{step.MethodName}' violates an After/Before constraint relative to '{after.MethodName}'.\");");
                sb.Append(indent).AppendLine("        }");
            }
        }

        foreach (var predecessor in allSteps.Where(s =>
                     !string.IsNullOrEmpty(s.Before)
                     && (string.Equals(s.Before, step.MethodName, StringComparison.Ordinal)
                         || string.Equals(s.Before, step.BindingName, StringComparison.OrdinalIgnoreCase))))
        {
            sb.Append(indent).AppendLine(
                $"        if (!state.AppliedOrder.Contains(\"{predecessor.MethodName}\"))");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine(
                $"            throw new InvalidOperationException(\"Step '{step.MethodName}' violates an After/Before constraint relative to '{predecessor.MethodName}'.\");");
            sb.Append(indent).AppendLine("        }");
        }

        if (string.IsNullOrEmpty(step.MutexGroup))
        {
            return;
        }

        foreach (var sibling in allSteps.Where(s =>
                     !string.Equals(s.MethodName, step.MethodName, StringComparison.Ordinal)
                     && string.Equals(s.MutexGroup, step.MutexGroup, StringComparison.Ordinal)))
        {
            var siblingProp = ToPropertyName(sibling.BindingName);
            sb.Append(indent).AppendLine($"        if (state.{siblingProp}Set)");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine(
                $"            throw new InvalidOperationException(\"Steps '{sibling.MethodName}' and '{step.MethodName}' both belong to mutex group '{step.MutexGroup}'.\");");
            sb.Append(indent).AppendLine("        }");
        }
    }

    private static void AppendBuildMethod(
        StringBuilder sb,
        string indent,
        GenerateBuilderModel model,
        List<BuilderStepModel> steps,
        string completeBuilderType)
    {
        var stepByMethod = steps.ToDictionary(static s => s.MethodName, StringComparer.Ordinal);

        sb.Append(indent).AppendLine("    /// <summary>");
        sb.Append(indent).AppendLine($"    /// Builds the product by invoking {model.HolderName}.{model.AssembleMethodName}.");
        sb.Append(indent).AppendLine("    /// </summary>");
        sb.Append(indent).AppendLine(
            $"    public static {model.ProductTypeDisplay} Build(this {completeBuilderType} builder)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var state = builder.State;");

        var args = new List<string>();
        foreach (var parameter in model.AssembleParameters)
        {
            if (!stepByMethod.TryGetValue(parameter.BoundStepMethodName, out var step))
            {
                args.Add("default");
                continue;
            }

            var prop = ToPropertyName(step.BindingName);
            if (step.Required)
            {
                args.Add($"state.{prop}!");
            }
            else
            {
                args.Add($"state.{prop}");
            }
        }

        var assembleTarget = model.AssembleIsStatic
            ? model.HolderFullyQualifiedName
            : $"new {model.HolderFullyQualifiedName}()";
        sb.Append(indent).AppendLine(
            $"        return {assembleTarget}.{model.AssembleMethodName}({string.Join(", ", args)});");
        sb.Append(indent).AppendLine("    }");
    }

    private static string ToPropertyName(string bindingName)
    {
        if (string.IsNullOrEmpty(bindingName))
        {
            return "Value";
        }

        return char.ToUpperInvariant(bindingName[0]) + bindingName.Substring(1);
    }

    private static string ToParameterName(string bindingName)
    {
        if (string.IsNullOrEmpty(bindingName))
        {
            return "value";
        }

        return char.ToLowerInvariant(bindingName[0]) + bindingName.Substring(1);
    }

}
