using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DesignPatterns.SourceGenerators.Syntax;

/// <summary>
/// Shared helpers for generated code headers, <c>#nullable enable</c>,
/// <c>[GeneratedCode]</c> attributes, and <c>#pragma warning disable</c>
/// directives. All SyntaxFactory files should route through these helpers
/// to keep generated output consistent across generators.
/// </summary>
internal static class GeneratedCodeHelper
{
    /// <summary>
    /// Creates the standard <c>// &lt;auto-generated /&gt;</c> header trivia
    /// followed by a generator-specific comment and a blank line.
    /// </summary>
    internal static SyntaxTriviaList CreateAutoGeneratedHeader(string generatorName) =>
        SyntaxFactory.TriviaList(
            SyntaxFactory.Comment("// <auto-generated />"),
            SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment($"// Generated by DesignPatterns.SourceGenerators.{generatorName}"),
            SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.EndOfLine("\n"));

    /// <summary>
    /// Wraps a type declaration into a normalized <see cref="CompilationUnitSyntax"/>
    /// with the auto-generated header, <c>#nullable enable</c>,
    /// <c>#pragma warning disable</c>, <c>System</c> using, and any additional usings.
    /// The type declaration is annotated with <c>[GeneratedCode]</c>.
    /// </summary>
    internal static CompilationUnitSyntax WrapInCompilationUnit(
        string? namespaceName,
        TypeDeclarationSyntax typeDeclaration,
        string generatorName,
        params string[] additionalUsings)
    {
        var annotatedType = AddGeneratedCodeAttribute(typeDeclaration);

        var compilationUnit = SyntaxFactory.CompilationUnit()
            .WithLeadingTrivia(CreateAutoGeneratedHeader(generatorName))
            .AddUsings(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System")));

        foreach (var additionalUsing in additionalUsings)
        {
            compilationUnit = compilationUnit.AddUsings(
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(additionalUsing)));
        }

        // Add #nullable enable directive after the usings.
        var nullableTrivia = SyntaxFactory.ParseTrailingTrivia("#nullable enable")
            .FirstOrDefault();

        if (!nullableTrivia.IsKind(SyntaxKind.None))
        {
            compilationUnit = compilationUnit
                .WithTrailingTrivia(SyntaxFactory.TriviaList(nullableTrivia));
        }

        MemberDeclarationSyntax member = annotatedType;
        if (!string.IsNullOrEmpty(namespaceName))
        {
            member = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(namespaceName!))
                .AddMembers(annotatedType);
        }

        return compilationUnit.AddMembers(member).NormalizeWhitespace();
    }

    /// <summary>
    /// Adds <c>[GeneratedCode("DesignPatterns.SourceGenerators", "1.0")]</c> attribute to a type declaration.
    /// Uses the fully-qualified name to avoid requiring a using directive.
    /// </summary>
    internal static T AddGeneratedCodeAttribute<T>(T typeDeclaration) where T : TypeDeclarationSyntax
    {
        var generatedCodeAttribute = SyntaxFactory.Attribute(
            SyntaxFactory.ParseName("global::System.CodeDom.Compiler.GeneratedCode"))
            .WithArgumentList(
                SyntaxFactory.AttributeArgumentList(
                    SyntaxFactory.SeparatedList(
                        new[]
                        {
                            SyntaxFactory.AttributeArgument(
                                SyntaxFactory.LiteralExpression(
                                    SyntaxKind.StringLiteralExpression,
                                    SyntaxFactory.Literal("DesignPatterns.SourceGenerators"))),
                            SyntaxFactory.AttributeArgument(
                                SyntaxFactory.LiteralExpression(
                                    SyntaxKind.StringLiteralExpression,
                                    SyntaxFactory.Literal("1.0"))),
                        })));

        var attributeList = SyntaxFactory.AttributeList(
            SyntaxFactory.SingletonSeparatedList(generatedCodeAttribute));

        return (T)typeDeclaration.AddAttributeLists(attributeList);
    }
}
