using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DesignPatterns.SourceGenerators.Syntax;

/// <summary>
/// Shared helpers for generated code headers, <c>#nullable enable</c>,
/// <c>[GeneratedCode]</c> attributes, and <c>#pragma warning disable</c>
/// directives. All SyntaxFactory files should route through these helpers
/// to keep generated output consistent across generators.
/// </summary>
internal static class GeneratedCodeHelper
{
    /// <summary>
    /// Creates the standard <c>// &lt;auto-generated /&gt;</c> header trivia
    /// followed by a generator-specific comment and a blank line.
    /// </summary>
    internal static SyntaxTriviaList CreateAutoGeneratedHeader(string generatorName) =>
        SyntaxFactory.TriviaList(
            SyntaxFactory.Comment("// <auto-generated />"),
            SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.Comment($"// Generated by DesignPatterns.SourceGenerators.{generatorName}"),
            SyntaxFactory.EndOfLine("\n"),
            SyntaxFactory.EndOfLine("\n"));

    /// <summary>
    /// Creates a <c>#nullable enable</c> preprocessor directive trivia.
    /// Parsed from text for Roslyn 4.8 compatibility (the
    /// <c>NullableDirectiveTrivia</c> factory overload is not available in 4.8).
    /// </summary>
    internal static SyntaxTrivia NullableEnableDirective =>
        SyntaxFactory.ParseLeadingTrivia("#nullable enable").First();

    /// <summary>
    /// Wraps a type declaration into a normalized <see cref="CompilationUnitSyntax"/>
    /// with the auto-generated header, <c>#nullable enable</c>,
    /// <c>System</c> using, and any additional usings.
    /// The type declaration is annotated with <c>[GeneratedCode]</c>.
    /// <para>
    /// <c>#nullable enable</c> is placed as leading trivia on the first member
    /// (namespace or type), after the using directives — not as trailing trivia
    /// on the compilation unit. This ensures the directive is in scope for all
    /// generated types.
    /// </para>
    /// </summary>
    internal static CompilationUnitSyntax WrapInCompilationUnit(
        string? namespaceName,
        TypeDeclarationSyntax typeDeclaration,
        string generatorName,
        params string[] additionalUsings)
    {
        var annotatedType = AddGeneratedCodeAttribute(typeDeclaration);

        var compilationUnit = SyntaxFactory.CompilationUnit()
            .WithLeadingTrivia(CreateAutoGeneratedHeader(generatorName))
            .AddUsings(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System")));

        foreach (var additionalUsing in additionalUsings)
        {
            // Skip "System" — it is already added unconditionally above.
            if (additionalUsing == "System")
            {
                continue;
            }

            compilationUnit = compilationUnit.AddUsings(
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(additionalUsing)));
        }

        MemberDeclarationSyntax member = annotatedType;
        if (!string.IsNullOrEmpty(namespaceName))
        {
            member = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(namespaceName!))
                .AddMembers(annotatedType);
        }

        // Place #nullable enable as leading trivia on the first member so it
        // appears after the using directives and before the namespace/type,
        // ensuring the nullable context applies to all generated declarations.
        member = member.WithLeadingTrivia(
            SyntaxFactory.TriviaList(NullableEnableDirective, SyntaxFactory.CarriageReturnLineFeed));

        return compilationUnit.AddMembers(member).NormalizeWhitespace();
    }

    /// <summary>
    /// Adds <c>[GeneratedCode("DesignPatterns.SourceGenerators", "1.0")]</c> attribute to a type declaration.
    /// Uses the fully-qualified name to avoid requiring a using directive.
    /// Preserves existing leading trivia (e.g., XML doc comments) so that it
    /// appears before the attribute, not after.
    /// </summary>
    internal static T AddGeneratedCodeAttribute<T>(T typeDeclaration) where T : TypeDeclarationSyntax
    {
        var existingLeadingTrivia = typeDeclaration.GetLeadingTrivia();

        // Strip existing leading trivia before adding the attribute so it
        // doesn't end up sandwiched between the attribute and the declaration.
        var stripped = existingLeadingTrivia.Count > 0
            ? typeDeclaration.WithoutLeadingTrivia()
            : typeDeclaration;

        var generatedCodeAttribute = SyntaxFactory.Attribute(
            SyntaxFactory.ParseName("global::System.CodeDom.Compiler.GeneratedCode"))
            .WithArgumentList(
                SyntaxFactory.AttributeArgumentList(
                    SyntaxFactory.SeparatedList(
                        new[]
                        {
                            SyntaxFactory.AttributeArgument(
                                SyntaxFactory.LiteralExpression(
                                    SyntaxKind.StringLiteralExpression,
                                    SyntaxFactory.Literal("DesignPatterns.SourceGenerators"))),
                            SyntaxFactory.AttributeArgument(
                                SyntaxFactory.LiteralExpression(
                                    SyntaxKind.StringLiteralExpression,
                                    SyntaxFactory.Literal("1.0"))),
                        })));

        var attributeList = SyntaxFactory.AttributeList(
            SyntaxFactory.SingletonSeparatedList(generatedCodeAttribute));

        var result = (T)stripped.AddAttributeLists(attributeList);

        // Re-attach existing leading trivia (e.g., /// <summary> XML doc) so
        // it appears before the [GeneratedCode] attribute, matching idiomatic
        // C# ordering: XML doc → attributes → declaration.
        if (existingLeadingTrivia.Count > 0)
        {
            result = result.WithLeadingTrivia(existingLeadingTrivia);
        }

        return result;
    }

    /// <summary>
    /// Creates a <c>/// &lt;summary&gt;</c> XML documentation comment
    /// suitable for attaching as leading trivia to a member or type declaration.
    /// </summary>
    internal static SyntaxTriviaList CreateXmlDoc(string summary)
    {
        var escaped = summary.Replace("<", "&lt;").Replace(">", "&gt;");
        var text = $"/// <summary>\n/// {escaped}\n/// </summary>\n";
        return SyntaxFactory.ParseLeadingTrivia(text);
    }

    /// <summary>
    /// Attaches a <c>/// &lt;summary&gt;</c> XML documentation comment
    /// to a member declaration as leading trivia.
    /// </summary>
    internal static T WithXmlDoc<T>(T member, string summary) where T : MemberDeclarationSyntax
        => member.WithLeadingTrivia(CreateXmlDoc(summary));
}
