using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DesignPatterns.SourceGenerators.Syntax;

internal static class SingletonSyntaxFactory
{
    private static readonly SyntaxTokenList PrivateStaticReadonlyModifiers =
        SyntaxFactory.TokenList(
            SyntaxFactory.Token(SyntaxKind.PrivateKeyword),
            SyntaxFactory.Token(SyntaxKind.StaticKeyword),
            SyntaxFactory.Token(SyntaxKind.ReadOnlyKeyword));

    public static CompilationUnitSyntax CreateCompilationUnit(
        string? namespaceName,
        string className,
        bool threadSafe,
        string? initializeAsync)
    {
        var partialClass = SyntaxFactory.ClassDeclaration(className)
            .WithModifiers(SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.PartialKeyword)));

        if (initializeAsync is null)
        {
            var member = CreateSingletonMembers(className, threadSafe);
            partialClass = partialClass.AddMembers(member.field, member.instanceProperty);
        }
        else
        {
            partialClass = partialClass.AddMembers(
                CreateAsyncSingletonField(className, threadSafe, initializeAsync),
                CreateGetInstanceAsyncMethod(className));
        }

        partialClass = GeneratedCodeHelper.AddGeneratedCodeAttribute(partialClass);
        partialClass = GeneratedCodeHelper.WithXmlDoc(partialClass, $"Provides the singleton instance for {className}.");

        MemberDeclarationSyntax namespaceMember = partialClass;
        if (!string.IsNullOrEmpty(namespaceName))
        {
            namespaceMember = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(namespaceName!))
                .AddMembers(partialClass);
        }

        var compilationUnit = SyntaxFactory.CompilationUnit()
            .WithLeadingTrivia(GeneratedCodeHelper.CreateAutoGeneratedHeader("GenerateSingletonGenerator"))
            .AddMembers(namespaceMember)
            .AddUsings(
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System")),
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Threading")));

        if (initializeAsync is not null)
        {
            compilationUnit = compilationUnit.AddUsings(
                SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Threading.Tasks")));
        }

        return compilationUnit.NormalizeWhitespace();
    }

    private static FieldDeclarationSyntax CreateAsyncSingletonField(
        string className,
        bool threadSafe,
        string initializeAsync)
    {
        var mode = threadSafe ? "LazyThreadSafetyMode.ExecutionAndPublication" : "LazyThreadSafetyMode.None";
        return (FieldDeclarationSyntax)SyntaxFactory.ParseMemberDeclaration(
            $"private static readonly Lazy<Task<{className}>> _instance = new Lazy<Task<{className}>>(async () => {{ var instance = new {className}(); await {initializeAsync}(instance, CancellationToken.None); return instance; }}, {mode});")!;
    }

    private static MethodDeclarationSyntax CreateGetInstanceAsyncMethod(string className) =>
        GeneratedCodeHelper.WithXmlDoc(
            (MethodDeclarationSyntax)SyntaxFactory.ParseMemberDeclaration(
                $"public static ValueTask<{className}> GetInstanceAsync() => new ValueTask<{className}>(_instance.Value);")!,
            "Gets the singleton instance after asynchronous initialization.");

    private static (FieldDeclarationSyntax field, PropertyDeclarationSyntax instanceProperty) CreateSingletonMembers(
        string className,
        bool threadSafe)
    {
        var typeSyntax = SyntaxFactory.ParseTypeName(className);
        var lazyType = SyntaxFactory.GenericName(SyntaxFactory.Identifier("Lazy"))
            .WithTypeArgumentList(
                SyntaxFactory.TypeArgumentList(
                    SyntaxFactory.SingletonSeparatedList(typeSyntax)));

        var lazyThreadSafetyMode = threadSafe
            ? SyntaxFactory.MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                SyntaxFactory.IdentifierName("LazyThreadSafetyMode"),
                SyntaxFactory.IdentifierName("ExecutionAndPublication"))
            : SyntaxFactory.MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                SyntaxFactory.IdentifierName("LazyThreadSafetyMode"),
                SyntaxFactory.IdentifierName("None"));

        var newInstanceLambda = SyntaxFactory.ParenthesizedLambdaExpression(
            SyntaxFactory.Block(
                SyntaxFactory.SingletonList<StatementSyntax>(
                    SyntaxFactory.ReturnStatement(
                        SyntaxFactory.ObjectCreationExpression(typeSyntax)
                            .WithArgumentList(SyntaxFactory.ArgumentList())))));

        var lazyCreation = SyntaxFactory.ObjectCreationExpression(lazyType)
            .WithArgumentList(
                SyntaxFactory.ArgumentList(
                    SyntaxFactory.SeparatedList<ArgumentSyntax>(
                        new[]
                        {
                            SyntaxFactory.Argument(newInstanceLambda),
                            SyntaxFactory.Argument(lazyThreadSafetyMode),
                        })));

        var field = SyntaxFactory.FieldDeclaration(
                SyntaxFactory.VariableDeclaration(lazyType)
                    .AddVariables(
                        SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("_instance"))
                            .WithInitializer(SyntaxFactory.EqualsValueClause(lazyCreation))))
            .WithModifiers(PrivateStaticReadonlyModifiers);

        var instanceProperty = GeneratedCodeHelper.WithXmlDoc(
            SyntaxFactory.PropertyDeclaration(typeSyntax, SyntaxFactory.Identifier("Instance"))
                .WithModifiers(
                    SyntaxFactory.TokenList(
                        SyntaxFactory.Token(SyntaxKind.PublicKeyword),
                        SyntaxFactory.Token(SyntaxKind.StaticKeyword)))
                .AddAccessorListAccessors(
                    SyntaxFactory.AccessorDeclaration(
                        SyntaxKind.GetAccessorDeclaration,
                        SyntaxFactory.Block(
                            SyntaxFactory.SingletonList<StatementSyntax>(
                                SyntaxFactory.ReturnStatement(
                                    SyntaxFactory.MemberAccessExpression(
                                        SyntaxKind.SimpleMemberAccessExpression,
                                        SyntaxFactory.IdentifierName("_instance"),
                                        SyntaxFactory.IdentifierName("Value"))))))),
            "Gets the singleton instance.");

        return (field, instanceProperty);
    }
}
