using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DesignPatterns.SourceGenerators.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DesignPatterns.SourceGenerators.Syntax;

internal static class WorkGraphSyntaxFactory
{
    public static CompilationUnitSyntax CreateCompilationUnit(WorkGraphEmitModel model)
    {
        var source = BuildSource(model);
        var tree = CSharpSyntaxTree.ParseText(source);
        var root = (CompilationUnitSyntax)tree.GetRoot();
        return root.NormalizeWhitespace();
    }

    public static string GetKeysClassName(string holderName) => holderName + "WorkStepKeys";

    public static string GetFacadeClassName(string holderName) => holderName + "WorkGraph";

    public static string ToConstantName(string key)
    {
        var parts = key.Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length == 0)
        {
            return "Key";
        }

        return string.Concat(parts.Select(ToPascalCaseSegment));
    }

    private static string ToPascalCaseSegment(string segment)
    {
        if (string.IsNullOrEmpty(segment))
        {
            return string.Empty;
        }

        if (segment.Length == 1)
        {
            return segment.ToUpperInvariant();
        }

        return char.ToUpperInvariant(segment[0]) + segment.Substring(1);
    }

    private static string BuildSource(WorkGraphEmitModel model)
    {
        var keysClass = GetKeysClassName(model.HolderName);
        var facadeClass = GetFacadeClassName(model.HolderName);
        var contextType = model.ContextFullyQualifiedDisplayString;
        var steps = model.Steps.ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by DesignPatterns.SourceGenerators.WorkGraphGenerator");
        sb.AppendLine();
        sb.AppendLine($"#pragma warning disable {GeneratedCodeHelper.PragmaWarningDisableCodes}");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using DesignPatterns.Behavioral;");
        sb.AppendLine();

        var indent = string.Empty;
        if (!string.IsNullOrEmpty(model.NamespaceName))
        {
            sb.AppendLine($"namespace {model.NamespaceName}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        sb.Append(indent).AppendLine("/// <summary>");
        sb.Append(indent).AppendLine($"/// Provides stable step ids for the {model.HolderName} work graph.");
        sb.Append(indent).AppendLine("/// </summary>");
        sb.Append(indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DesignPatterns.SourceGenerators\", \"1.0\")]");
        sb.Append(indent).AppendLine($"public static partial class {keysClass}");
        sb.Append(indent).AppendLine("{");
        foreach (var step in steps.OrderBy(static s => s.StepId, StringComparer.Ordinal))
        {
            sb.Append(indent).AppendLine("    /// <summary>");
            sb.Append(indent).AppendLine($"    /// The id for the {step.StepId} work step.");
            sb.Append(indent).AppendLine("    /// </summary>");
            sb.Append(indent).AppendLine($"    public const string {step.ConstantName} = \"{EscapeString(step.StepId)}\";");
        }

        sb.Append(indent).AppendLine("}");
        sb.AppendLine();

        sb.Append(indent).AppendLine("/// <summary>");
        sb.Append(indent).AppendLine($"/// Builds an IWorkGraph for the {model.HolderName} attribute catalog.");
        sb.Append(indent).AppendLine("/// </summary>");
        sb.Append(indent).AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"DesignPatterns.SourceGenerators\", \"1.0\")]");
        sb.Append(indent).AppendLine($"public static partial class {facadeClass}");
        sb.Append(indent).AppendLine("{");

        sb.Append(indent).AppendLine("    /// <summary>");
        sb.Append(indent).AppendLine("    /// Creates a work graph by resolving each catalog step id through <paramref name=\"resolveById\"/>.");
        sb.Append(indent).AppendLine("    /// </summary>");
        sb.Append(indent).AppendLine($"    public static global::DesignPatterns.Behavioral.IWorkGraph<{contextType}> Create(global::System.Func<string, global::DesignPatterns.Behavioral.IWorkStep<{contextType}>> resolveById)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        if (resolveById is null)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            throw new global::System.ArgumentNullException(nameof(resolveById));");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine();
        sb.Append(indent).AppendLine($"        var builder = new global::DesignPatterns.Behavioral.WorkGraphBuilder<{contextType}>();");
        foreach (var step in steps.OrderBy(static s => s.StepId, StringComparer.Ordinal))
        {
            var keyRef = $"{keysClass}.{step.ConstantName}";
            if (step.DependsOnConstantNames.Count == 0)
            {
                sb.Append(indent).AppendLine($"        builder.Add({keyRef}, resolveById({keyRef}));");
            }
            else
            {
                var deps = string.Join(", ", step.DependsOnConstantNames.Select(c => $"{keysClass}.{c}"));
                sb.Append(indent).AppendLine($"        builder.Add({keyRef}, resolveById({keyRef}), {deps});");
            }
        }

        sb.Append(indent).AppendLine("        return builder.Build();");
        sb.Append(indent).AppendLine("    }");
        sb.AppendLine();

        sb.Append(indent).AppendLine("    /// <summary>");
        sb.Append(indent).AppendLine("    /// Creates a work graph from a dictionary of catalog step ids to step instances.");
        sb.Append(indent).AppendLine("    /// </summary>");
        sb.Append(indent).AppendLine($"    public static global::DesignPatterns.Behavioral.IWorkGraph<{contextType}> Create(global::System.Collections.Generic.IReadOnlyDictionary<string, global::DesignPatterns.Behavioral.IWorkStep<{contextType}>> steps)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        if (steps is null)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).AppendLine("            throw new global::System.ArgumentNullException(nameof(steps));");
        sb.Append(indent).AppendLine("        }");
        sb.Append(indent).AppendLine();
        sb.Append(indent).AppendLine($"        return Create(id => steps[id]);");
        sb.Append(indent).AppendLine("    }");

        sb.Append(indent).AppendLine("}");

        if (!string.IsNullOrEmpty(model.NamespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
